/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bniobemminqwvycjkbcn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaW9iZW1taW5xd3Z5Y2prYmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMjE3NTQsImV4cCI6MjA4NzU5Nzc1NH0.n9IxwbIiIdqmHjwGQb-PqsD8j-v7uZtwF7h1lXt_Lho"